# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
repository: https://github.com/onemorejsdeveloper/docs-as-code
title: ADAMANT. Docs-as-code
description: >-
  ADAMANT Docs-as-code test site
url: "https://onemorejsdeveloper.github.io/docs-as-code/"
twitter_username: onemorejsdeveloper
github_username:  onemorejsdeveloper
header_pages:
 - docs.html

# Build settings
markdown: kramdown

kramdown: 
  input: GFM
theme: minima
plugins:
  - jekyll-feed

permalink: /:slug

collections:
  docs:
    output: true

defaults:
  - scope:
      path: "_docs"
    values:
      layout: "doc"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
